newyork = [
"Adams village, New York",
"Addison village, New York",
"Afton village, New York",
"Airmont village, New York",
"Akron village, New York",
"Albany city, New York",
"Albion village, New York",
"Alden village, New York",
"Alexander village, New York",
"Alexandria Bay village, New York",
"Alfred village, New York",
"Allegany village, New York",
"Almond village, New York",
"Altamont village, New York",
"Ames village, New York",
"Amityville village, New York",
"Amsterdam city, New York",
"Andover village, New York",
"Angelica village, New York",
"Angola village, New York",
"Antwerp village, New York",
"Arcade village, New York",
"Ardsley village, New York",
"Argyle village, New York",
"Arkport village, New York",
"Asharoken village, New York",
"Athens village, New York",
"Atlantic Beach village, New York",
"Attica village, New York",
"Auburn city, New York",
"Aurora village, New York",
"Avoca village, New York",
"Avon village, New York",
"Babylon village, New York",
"Bainbridge village, New York",
"Baldwinsville village, New York",
"Ballston Spa village, New York",
"Barker village, New York",
"Batavia city, New York",
"Bath village, New York",
"Baxter Estates village, New York",
"Bayville village, New York",
"Beacon city, New York",
"Bellerose village, New York",
"Belle Terre village, New York",
"Bellport village, New York",
"Belmont village, New York",
"Bemus Point village, New York",
"Bergen village, New York",
"Binghamton city, New York",
"Black River village, New York",
"Blasdell village, New York",
"Bloomfield village, New York",
"Bloomingburg village, New York",
"Bolivar village, New York",
"Boonville village, New York",
"Brewster village, New York",
"Briarcliff Manor village, New York",
"Brightwaters village, New York",
"Broadalbin village, New York",
"Brockport village, New York",
"Brocton village, New York",
"Bronxville village, New York",
"Brookville village, New York",
"Brownville village, New York",
"Brushton village, New York",
"Buchanan village, New York",
"Buffalo city, New York",
"Burdett village, New York",
"Burke village, New York",
"Caledonia village, New York",
"Cambridge village, New York",
"Camden village, New York",
"Camillus village, New York",
"Canajoharie village, New York",
"Canandaigua city, New York",
"Canaseraga village, New York",
"Canastota village, New York",
"Candor village, New York",
"Canisteo village, New York",
"Canton village, New York",
"Cape Vincent village, New York",
"Carthage village, New York",
"Cassadaga village, New York",
"Castile village, New York",
"Castleton-on-Hudson village, New York",
"Castorland village, New York",
"Cato village, New York",
"Catskill village, New York",
"Cattaraugus village, New York",
"Cayuga village, New York",
"Cayuga Heights village, New York",
"Cazenovia village, New York",
"Cedarhurst village, New York",
"Celoron village, New York",
"Central Square village, New York",
"Centre Island village, New York",
"Champlain village, New York",
"Chateaugay village, New York",
"Chatham village, New York",
"Chaumont village, New York",
"Cherry Creek village, New York",
"Cherry Valley village, New York",
"Chester village, New York",
"Chestnut Ridge village, New York",
"Chittenango village, New York",
"Churchville village, New York",
"Clayton village, New York",
"Clayville village, New York",
"Cleveland village, New York",
"Clifton Springs village, New York",
"Clinton village, New York",
"Clyde village, New York",
"Cobleskill village, New York",
"Cohocton village, New York",
"Cohoes city, New York",
"Cold Brook village, New York",
"Cold Spring village, New York",
"Colonie village, New York",
"Constableville village, New York",
"Cooperstown village, New York",
"Copenhagen village, New York",
"Corfu village, New York",
"Corinth village, New York",
"Corning city, New York",
"Cornwall-on-Hudson village, New York",
"Cortland city, New York",
"Cove Neck village, New York",
"Coxsackie village, New York",
"Croghan village, New York",
"Croton-on-Hudson village, New York",
"Cuba village, New York",
"Dannemora village, New York",
"Dansville village, New York",
"Deferiet village, New York",
"Delanson village, New York",
"Delevan village, New York",
"Delhi village, New York",
"Depew village, New York",
"Deposit village, New York",
"Dering Harbor village, New York",
"DeRuyter village, New York",
"Dexter village, New York",
"Dobbs Ferry village, New York",
"Dolgeville village, New York",
"Dresden village, New York",
"Dryden village, New York",
"Dundee village, New York",
"Dunkirk city, New York",
"Earlville village, New York",
"East Aurora village, New York",
"East Hampton village, New York",
"East Hills village, New York",
"East Nassau village, New York",
"East Rochester village, New York",
"East Rockaway village, New York",
"East Syracuse village, New York",
"East Williston village, New York",
"Elba village, New York",
"Elbridge village, New York",
"Ellenville village, New York",
"Ellicottville village, New York",
"Ellisburg village, New York",
"Elmira city, New York",
"Elmira Heights village, New York",
"Elmsford village, New York",
"Endicott village, New York",
"Esperance village, New York",
"Evans Mills village, New York",
"Fabius village, New York",
"Fair Haven village, New York",
"Fairport village, New York",
"Falconer village, New York",
"Farmingdale village, New York",
"Farnham village, New York",
"Fayetteville village, New York",
"Fishkill village, New York",
"Fleischmanns village, New York",
"Floral Park village, New York",
"Florida village, New York",
"Flower Hill village, New York",
"Fonda village, New York",
"Fort Ann village, New York",
"Fort Edward village, New York",
"Fort Johnson village, New York",
"Fort Plain village, New York",
"Frankfort village, New York",
"Franklin village, New York",
"Franklinville village, New York",
"Fredonia village, New York",
"Freeport village, New York",
"Freeville village, New York",
"Fulton city, New York",
"Fultonville village, New York",
"Gainesville village, New York",
"Galway village, New York",
"Garden City village, New York",
"Geneseo village, New York",
"Geneva city, New York",
"Gilbertsville village, New York",
"Glen Cove city, New York",
"Glen Park village, New York",
"Glens Falls city, New York",
"Gloversville city, New York",
"Goshen village, New York",
"Gouverneur village, New York",
"Gowanda village, New York",
"Grand View-on-Hudson village, New York",
"Granville village, New York",
"Great Neck village, New York",
"Great Neck Estates village, New York",
"Great Neck Plaza village, New York",
"Greene village, New York",
"Green Island village, New York",
"Greenport village, New York",
"Greenwich village, New York",
"Greenwood Lake village, New York",
"Groton village, New York",
"Hagaman village, New York",
"Hamburg village, New York",
"Hamilton village, New York",
"Hammond village, New York",
"Hammondsport village, New York",
"Hancock village, New York",
"Hannibal village, New York",
"Harriman village, New York",
"Harrison village, New York",
"Harrisville village, New York",
"Hastings-on-Hudson village, New York",
"Haverstraw village, New York",
"Head of the Harbor village, New York",
"Hempstead village, New York",
"Herkimer village, New York",
"Heuvelton village, New York",
"Hewlett Bay Park village, New York",
"Hewlett Harbor village, New York",
"Hewlett Neck village, New York",
"Highland Falls village, New York",
"Hillburn village, New York",
"Hilton village, New York",
"Hobart village, New York",
"Holland Patent village, New York",
"Holley village, New York",
"Homer village, New York",
"Honeoye Falls village, New York",
"Hoosick Falls village, New York",
"Hornell city, New York",
"Horseheads village, New York",
"Hudson city, New York",
"Hudson Falls village, New York",
"Hunter village, New York",
"Huntington Bay village, New York",
"Ilion village, New York",
"Interlaken village, New York",
"Irvington village, New York",
"Islandia village, New York",
"Island Park village, New York",
"Ithaca city, New York",
"Jamestown city, New York",
"Jeffersonville village, New York",
"Johnson City village, New York",
"Johnstown city, New York",
"Jordan village, New York",
"Kaser village, New York",
"Kenmore village, New York",
"Kensington village, New York",
"Kinderhook village, New York",
"Kings Point village, New York",
"Kingston city, New York",
"Kiryas Joel village, New York",
"Lackawanna city, New York",
"Lacona village, New York",
"Lake George village, New York",
"Lake Grove village, New York",
"Lake Placid village, New York",
"Lake Success village, New York",
"Lakewood village, New York",
"Lancaster village, New York",
"Lansing village, New York",
"Larchmont village, New York",
"Lattingtown village, New York",
"Laurel Hollow village, New York",
"Laurens village, New York",
"Lawrence village, New York",
"Leicester village, New York",
"Le Roy village, New York",
"Lewiston village, New York",
"Liberty village, New York",
"Lima village, New York",
"Lindenhurst village, New York",
"Lisle village, New York",
"Little Falls city, New York",
"Little Valley village, New York",
"Liverpool village, New York",
"Livonia village, New York",
"Lloyd Harbor village, New York",
"Lockport city, New York",
"Lodi village, New York",
"Long Beach city, New York",
"Lowville village, New York",
"Lynbrook village, New York",
"Lyndonville village, New York",
"Lyons Falls village, New York",
"McGraw village, New York",
"Madison village, New York",
"Malone village, New York",
"Malverne village, New York",
"Mamaroneck village, New York",
"Manchester village, New York",
"Manlius village, New York",
"Mannsville village, New York",
"Manorhaven village, New York",
"Marathon village, New York",
"Marcellus village, New York",
"Margaretville village, New York",
"Massapequa Park village, New York",
"Massena village, New York",
"Matinecock village, New York",
"Maybrook village, New York",
"Mayfield village, New York",
"Mayville village, New York",
"Mechanicville city, New York",
"Medina village, New York",
"Menands village, New York",
"Meridian village, New York",
"Mexico village, New York",
"Middleburgh village, New York",
"Middleport village, New York",
"Middletown city, New York",
"Middleville village, New York",
"Milford village, New York",
"Millbrook village, New York",
"Millerton village, New York",
"Mill Neck village, New York",
"Millport village, New York",
"Mineola village, New York",
"Minoa village, New York",
"Mohawk village, New York",
"Monroe village, New York",
"Montebello village, New York",
"Montgomery village, New York",
"Monticello village, New York",
"Montour Falls village, New York",
"Moravia village, New York",
"Morris village, New York",
"Morristown village, New York",
"Morrisville village, New York",
"Mount Kisco village, New York",
"Mount Morris village, New York",
"Mount Vernon city, New York",
"Munnsville village, New York",
"Munsey Park village, New York",
"Muttontown village, New York",
"Naples village, New York",
"Nassau village, New York",
"Nelliston village, New York",
"Nelsonville village, New York",
"Newark village, New York",
"Newark Valley village, New York",
"New Berlin village, New York",
"Newburgh city, New York",
"New Hartford village, New York",
"New Hempstead village, New York",
"New Hyde Park village, New York",
"New Paltz village, New York",
"Newport village, New York",
"New Rochelle city, New York",
"New Square village, New York",
"New York city, New York",
"New York Mills village, New York",
"Niagara Falls city, New York",
"Nichols village, New York",
"Nissequogue village, New York",
"North Collins village, New York",
"North Haven village, New York",
"North Hills village, New York",
"North Hornell village, New York",
"Northport village, New York",
"North Syracuse village, New York",
"North Tonawanda city, New York",
"Northville village, New York",
"Norwich city, New York",
"Norwood village, New York",
"Nunda village, New York",
"Nyack village, New York",
"Oakfield village, New York",
"Ocean Beach village, New York",
"Odessa village, New York",
"Ogdensburg city, New York",
"Old Brookville village, New York",
"Old Field village, New York",
"Old Westbury village, New York",
"Olean city, New York",
"Oneida city, New York",
"Oneida Castle village, New York",
"Oneonta city, New York",
"Orchard Park village, New York",
"Oriskany village, New York",
"Oriskany Falls village, New York",
"Ossining village, New York",
"Oswego city, New York",
"Otego village, New York",
"Otisville village, New York",
"Ovid village, New York",
"Owego village, New York",
"Oxford village, New York",
"Oyster Bay Cove village, New York",
"Painted Post village, New York",
"Palatine Bridge village, New York",
"Palmyra village, New York",
"Panama village, New York",
"Parish village, New York",
"Patchogue village, New York",
"Pawling village, New York",
"Peekskill city, New York",
"Pelham village, New York",
"Pelham Manor village, New York",
"Penn Yan village, New York",
"Perry village, New York",
"Phelps village, New York",
"Philadelphia village, New York",
"Philmont village, New York",
"Phoenix village, New York",
"Piermont village, New York",
"Pittsford village, New York",
"Plandome village, New York",
"Plandome Heights village, New York",
"Plandome Manor village, New York",
"Plattsburgh city, New York",
"Pleasantville village, New York",
"Poland village, New York",
"Pomona village, New York",
"Poquott village, New York",
"Port Byron village, New York",
"Port Chester village, New York",
"Port Dickinson village, New York",
"Port Jefferson village, New York",
"Port Jervis city, New York",
"Port Leyden village, New York",
"Portville village, New York",
"Port Washington North village, New York",
"Potsdam village, New York",
"Poughkeepsie city, New York",
"Pulaski village, New York",
"Quogue village, New York",
"Ravena village, New York",
"Red Creek village, New York",
"Red Hook village, New York",
"Remsen village, New York",
"Rensselaer city, New York",
"Rensselaer Falls village, New York",
"Rhinebeck village, New York",
"Richburg village, New York",
"Richfield Springs village, New York",
"Richmondville village, New York",
"Richville village, New York",
"Riverside village, New York",
"Rochester city, New York",
"Rockville Centre village, New York",
"Rome city, New York",
"Roslyn village, New York",
"Roslyn Estates village, New York",
"Roslyn Harbor village, New York",
"Round Lake village, New York",
"Rouses Point village, New York",
"Rushville village, New York",
"Russell Gardens village, New York",
"Rye city, New York",
"Rye Brook village, New York",
"Sackets Harbor village, New York",
"Saddle Rock village, New York",
"Sagaponack village, New York",
"Sag Harbor village, New York",
"St. Johnsville village, New York",
"Salamanca city, New York",
"Saltaire village, New York",
"Sands Point village, New York",
"Sandy Creek village, New York",
"Saranac Lake village, New York",
"Saratoga Springs city, New York",
"Saugerties village, New York",
"Savona village, New York",
"Scarsdale village, New York",
"Schaghticoke village, New York",
"Schenectady city, New York",
"Schoharie village, New York",
"Schuylerville village, New York",
"Scotia village, New York",
"Scottsville village, New York",
"Sea Cliff village, New York",
"Sharon Springs village, New York",
"Sherburne village, New York",
"Sherman village, New York",
"Sherrill city, New York",
"Shoreham village, New York",
"Shortsville village, New York",
"Sidney village, New York",
"Silver Creek village, New York",
"Silver Springs village, New York",
"Sinclairville village, New York",
"Skaneateles village, New York",
"Sleepy Hollow village, New York",
"Sloan village, New York",
"Sloatsburg village, New York",
"Smyrna village, New York",
"Sodus village, New York",
"Sodus Point village, New York",
"Solvay village, New York",
"Southampton village, New York",
"South Blooming Grove village, New York",
"South Corning village, New York",
"South Dayton village, New York",
"South Floral Park village, New York",
"South Glens Falls village, New York",
"South Nyack village, New York",
"Speculator village, New York",
"Spencer village, New York",
"Spencerport village, New York",
"Spring Valley village, New York",
"Springville village, New York",
"Stamford village, New York",
"Stewart Manor village, New York",
"Stillwater village, New York",
"Suffern village, New York",
"Sylvan Beach village, New York",
"Syracuse city, New York",
"Tannersville village, New York",
"Tarrytown village, New York",
"Theresa village, New York",
"Thomaston village, New York",
"Tivoli village, New York",
"Tonawanda city, New York",
"Troy city, New York",
"Trumansburg village, New York",
"Tuckahoe village, New York",
"Tully village, New York",
"Tupper Lake village, New York",
"Turin village, New York",
"Tuxedo Park village, New York",
"Unadilla village, New York",
"Union Springs village, New York",
"Unionville village, New York",
"Upper Brookville village, New York",
"Upper Nyack village, New York",
"Utica city, New York",
"Valatie village, New York",
"Valley Falls village, New York",
"Valley Stream village, New York",
"Van Etten village, New York",
"Vernon village, New York",
"Victor village, New York",
"Victory village, New York",
"Village of the Branch village, New York",
"Voorheesville village, New York",
"Waddington village, New York",
"Walden village, New York",
"Walton village, New York",
"Wampsville village, New York",
"Wappingers Falls village, New York",
"Warsaw village, New York",
"Warwick village, New York",
"Washingtonville village, New York",
"Waterford village, New York",
"Waterloo village, New York",
"Watertown city, New York",
"Waterville village, New York",
"Watervliet city, New York",
"Watkins Glen village, New York",
"Waverly village, New York",
"Wayland village, New York",
"Webster village, New York",
"Weedsport village, New York",
"Wellsburg village, New York",
"Wellsville village, New York",
"Wesley Hills village, New York",
"Westbury village, New York",
"West Carthage village, New York",
"Westfield village, New York",
"Westhampton Beach village, New York",
"West Hampton Dunes village, New York",
"West Haverstraw village, New York",
"West Winfield village, New York",
"Whitehall village, New York",
"White Plains city, New York",
"Whitesboro village, New York",
"Whitney Point village, New York",
"Williamsville village, New York",
"Williston Park village, New York",
"Wilson village, New York",
"Windsor village, New York",
"Wolcott village, New York",
"Woodbury village, New York",
"Woodridge village, New York",
"Woodsburgh village, New York",
"Wurtsboro village, New York",
"Wyoming village, New York",
"Yonkers city, New York",
"Yorkville village, New York",
"Youngstown village, New York"
]